version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend_main"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"