version: "3.8"

services:
  backend:
    container_name: hekopay-backend1
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    
    volumes:
      - .:/app